import type { DataType } from "@gatewai.studio/core";
import { defineMetadata } from "@gatewai.studio/node-sdk";
import {
	type StarterNodeConfig,
	StarterNodeConfigSchema,
	StarterResultSchema,
	starterConfig,
} from "./shared/index.js";

export { type StarterNodeConfig, StarterNodeConfigSchema, StarterResultSchema };

/**
 * Gatewai Node Metadata Definition
 *
 * This metadata object defines the node's interface, identity, handles, capabilities,
 * and runtime validation rules across the Gatewai engine, Artifex CLI, and browser UI.
 */
export const metadata = defineMetadata({
	// --- 1. Identity & Versioning ---
	// Unique PascalCase string identifier (e.g. "ApplyLUT", "Starter", "Blur").
	// When introducing breaking changes, create a new package (e.g. "Starter_v2") and point baseType to "Starter".
	type: "Starter",
	version: 1,
	baseType: undefined,

	// Human-readable title displayed in the node canvas header and UI menus.
	displayName: "Starter Node",

	// Crisp 1-2 sentence description explaining what the node does (shown in tooltips and agent catalogs).
	description:
		"Starter transformation node template for building custom Gatewai nodes with dynamic modulation.",

	// Category for organizing nodes in the sidebar palette ("Media", "AI", "Generators", "Audio", "Utilities").
	category: "Media",
	subcategory: undefined,

	// --- 2. Visibility Flags ---
	// Controls whether the node appears in the sidebar palette (defaults to true).
	showInSidebar: true,
	// Controls whether the node appears in the quick-access search menu (defaults to true).
	showInQuickAccess: true,

	// --- 3. Execution Characteristics ---
	// `isTerminal`:
	// - false: Intermediate/client transformer node (e.g. Blur, Delay, ApplyLUT) that processes locally or appends operations without requiring backend processing.
	// - true: Node that requires backend processing on the server worker (e.g. AI generations via Fal AI like ImageGen, VideoGen, TextToSpeech, LLM, or server exports).
	isTerminal: false,

	// `isTransient`:
	// - true: Results are temporary/intermediate VirtualMedia objects (not stored in permanent DB asset storage).
	// - false: Output assets are permanently saved to database/cloud storage.
	isTransient: true,

	// --- 4. Sockets & Handles ---
	// Static input and output sockets declared on the node component.
	handles: {
		inputs: [
			{
				dataTypes: ["Image", "Video"] as DataType[],
				required: true,
				label: "Input",
				order: 0,
				description: "Primary visual media stream to transform.",
			},
		],
		outputs: [
			{
				dataTypes: ["Image", "Video"] as DataType[],
				label: "Result",
				order: 0,
				description: "Transformed visual media output stream.",
			},
		],
	},

	// Variable (dynamic) input sockets (e.g., dynamic signal modulation or extra audio tracks).
	variableInputs: {
		enabled: true,
		dataTypes: ["Signal", "Number"] as DataType[],
	},

	// Variable (dynamic) output sockets (e.g., AI branching or dynamic channel splitting).
	variableOutputs: {
		enabled: false,
	},

	// --- 5. Config, Schemas, & Bindable Handles ---
	// Zod schema for validating the node's config at runtime.
	configSchema: StarterNodeConfigSchema,

	// Default configuration values matching the schema.
	defaultConfig: {
		strength: 1.0,
		mode: "standard",
		enabled: true,
	} as StarterNodeConfig,

	// Dynamic config sockets generated by configBuilder() with `bindable: true`.
	configHandles: starterConfig.configHandles,

	// Zod schema for validating the output results of this node.
	resultSchema: StarterResultSchema,

	// --- 6. Pricing & Validation (Optional) ---
	// Cost estimation function (config, inputs) => number of credits.
	pricing: (_config) => 0,
	isDynamicPricing: false,

	// Pre-execution validation function returning { [fieldId]: errorMessage } or null if valid.
	validation: (config, _inputs) => {
		if (config && typeof config.strength === "number" && config.strength < 0) {
			return { strength: "Strength cannot be negative." };
		}
		return null;
	},
});
