// This file is auto-generated by scripts/generate-nodes-registry.mjs. Do not edit.
import type { NodeRegistry } from "@gatewai.studio/node-sdk/server";
import { registerWebGPURenderer, audioRegistry } from "@gatewai.studio/node-sdk/browser";

export async function registerStaticNodes(registry: NodeRegistry): Promise<void> {
		try {
			const node_apply_lut = await import("@gatewai.studio/node-lut/server");
			if (node_apply_lut.default) registry.register(node_apply_lut.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-lut:", e);
		}

		try {
			const node_audio_compressor = await import("@gatewai.studio/node-audio-compressor/server");
			if (node_audio_compressor.default) registry.register(node_audio_compressor.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-audio-compressor:", e);
		}

		try {
			const node_audio_delay = await import("@gatewai.studio/node-audio-delay/server");
			if (node_audio_delay.default) registry.register(node_audio_delay.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-audio-delay:", e);
		}

		try {
			const node_audio_fade = await import("@gatewai.studio/node-audio-fade/server");
			if (node_audio_fade.default) registry.register(node_audio_fade.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-audio-fade:", e);
		}

		try {
			const node_audio_generator = await import("@gatewai.studio/node-audio-generator/server");
			if (node_audio_generator.default) registry.register(node_audio_generator.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-audio-generator:", e);
		}

		try {
			const node_audio_noise_gate = await import("@gatewai.studio/node-audio-noise-gate/server");
			if (node_audio_noise_gate.default) registry.register(node_audio_noise_gate.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-audio-noise-gate:", e);
		}

		try {
			const node_audio_parametric_eq = await import("@gatewai.studio/node-audio-parametric-eq/server");
			if (node_audio_parametric_eq.default) registry.register(node_audio_parametric_eq.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-audio-parametric-eq:", e);
		}

		try {
			const node_audio_reverb = await import("@gatewai.studio/node-audio-reverb/server");
			if (node_audio_reverb.default) registry.register(node_audio_reverb.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-audio-reverb:", e);
		}

		try {
			const node_blur = await import("@gatewai.studio/node-blur/server");
			if (node_blur.default) registry.register(node_blur.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-blur:", e);
		}

		try {
			const node_canvas_generator = await import("@gatewai.studio/node-canvas-generator/server");
			if (node_canvas_generator.default) registry.register(node_canvas_generator.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-canvas-generator:", e);
		}

		try {
			const node_caption_editor = await import("@gatewai.studio/node-caption-editor/server");
			if (node_caption_editor.default) registry.register(node_caption_editor.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-caption-editor:", e);
		}

		try {
			const node_caption_generator = await import("@gatewai.studio/node-caption-generator/server");
			if (node_caption_generator.default) registry.register(node_caption_generator.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-caption-generator:", e);
		}

		try {
			const node_channel_merger = await import("@gatewai.studio/node-channel-merger/server");
			if (node_channel_merger.default) registry.register(node_channel_merger.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-channel-merger:", e);
		}

		try {
			const node_channel_splitter = await import("@gatewai.studio/node-channel-splitter/server");
			if (node_channel_splitter.default) registry.register(node_channel_splitter.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-channel-splitter:", e);
		}

		try {
			const node_color_balance = await import("@gatewai.studio/node-color-balance/server");
			if (node_color_balance.default) registry.register(node_color_balance.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-color-balance:", e);
		}

		try {
			const node_colorkey = await import("@gatewai.studio/node-colorkey/server");
			if (node_colorkey.default) registry.register(node_colorkey.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-colorkey:", e);
		}

		try {
			const node_compositor = await import("@gatewai.studio/node-compositor/server");
			if (node_compositor.default) registry.register(node_compositor.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-compositor:", e);
		}

		try {
			const node_corner_pin = await import("@gatewai.studio/node-corner-pin/server");
			if (node_corner_pin.default) registry.register(node_corner_pin.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-corner-pin:", e);
		}

		try {
			const node_crop = await import("@gatewai.studio/node-crop/server");
			if (node_crop.default) registry.register(node_crop.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-crop:", e);
		}

		try {
			const node_curves = await import("@gatewai.studio/node-curves/server");
			if (node_curves.default) registry.register(node_curves.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-curves:", e);
		}

		try {
			const node_depth_map = await import("@gatewai.studio/node-depth-map/server");
			if (node_depth_map.default) registry.register(node_depth_map.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-depth-map:", e);
		}

		try {
			const node_displacement_map = await import("@gatewai.studio/node-displacement-map/server");
			if (node_displacement_map.default) registry.register(node_displacement_map.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-displacement-map:", e);
		}

		try {
			const node_edit_video = await import("@gatewai.studio/node-edit-video/server");
			if (node_edit_video.default) registry.register(node_edit_video.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-edit-video:", e);
		}

		try {
			const node_export = await import("@gatewai.studio/node-export/server");
			if (node_export.default) registry.register(node_export.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-export:", e);
		}

		try {
			const node_extract_frame = await import("@gatewai.studio/node-extract-frame/server");
			if (node_extract_frame.default) registry.register(node_extract_frame.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-extract-frame:", e);
		}

		try {
			const node_extract_lut = await import("@gatewai.studio/node-extract-lut/server");
			if (node_extract_lut.default) registry.register(node_extract_lut.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-extract-lut:", e);
		}

		try {
			const node_extract_object = await import("@gatewai.studio/node-extract-object/server");
			if (node_extract_object.default) registry.register(node_extract_object.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-extract-object:", e);
		}

		try {
			const node_film_grain = await import("@gatewai.studio/node-film-grain/server");
			if (node_film_grain.default) registry.register(node_film_grain.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-film-grain:", e);
		}

		try {
			const node_flip = await import("@gatewai.studio/node-flip/server");
			if (node_flip.default) registry.register(node_flip.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-flip:", e);
		}

		try {
			const node_gradient_map = await import("@gatewai.studio/node-gradient-map/server");
			if (node_gradient_map.default) registry.register(node_gradient_map.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-gradient-map:", e);
		}

		try {
			const node_halftone_screen = await import("@gatewai.studio/node-halftone-screen/server");
			if (node_halftone_screen.default) registry.register(node_halftone_screen.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-halftone-screen:", e);
		}

		try {
			const node_high_pass = await import("@gatewai.studio/node-high-pass/server");
			if (node_high_pass.default) registry.register(node_high_pass.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-high-pass:", e);
		}

		try {
			const node_image_gen = await import("@gatewai.studio/node-image-gen/server");
			if (node_image_gen.default) registry.register(node_image_gen.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-image-gen:", e);
		}

		try {
			const node_import = await import("@gatewai.studio/node-import/server");
			if (node_import.default) registry.register(node_import.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-import:", e);
		}

		try {
			const node_kenburns = await import("@gatewai.studio/node-kenburns/server");
			if (node_kenburns.default) registry.register(node_kenburns.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-kenburns:", e);
		}

		try {
			const node_layer_style = await import("@gatewai.studio/node-layer-style/server");
			if (node_layer_style.default) registry.register(node_layer_style.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-layer-style:", e);
		}

		try {
			const node_levels = await import("@gatewai.studio/node-levels/server");
			if (node_levels.default) registry.register(node_levels.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-levels:", e);
		}

		try {
			const node_lip_sync = await import("@gatewai.studio/node-lip-sync/server");
			if (node_lip_sync.default) registry.register(node_lip_sync.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-lip-sync:", e);
		}

		try {
			const node_liquify = await import("@gatewai.studio/node-liquify/server");
			if (node_liquify.default) registry.register(node_liquify.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-liquify:", e);
		}

		try {
			const node_llm = await import("@gatewai.studio/node-llm/server");
			if (node_llm.default) registry.register(node_llm.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-llm:", e);
		}

		try {
			const node_lottie = await import("@gatewai.studio/node-lottie/server");
			if (node_lottie.default) registry.register(node_lottie.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-lottie:", e);
		}

		try {
			const node_mask_math = await import("@gatewai.studio/node-mask-math/server");
			if (node_mask_math.default) registry.register(node_mask_math.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-mask-math:", e);
		}

		try {
			const node_media_cut = await import("@gatewai.studio/node-media-cut/server");
			if (node_media_cut.default) registry.register(node_media_cut.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-media-cut:", e);
		}

		try {
			const node_mesh_warp = await import("@gatewai.studio/node-mesh-warp/server");
			if (node_mesh_warp.default) registry.register(node_mesh_warp.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-mesh-warp:", e);
		}

		try {
			const node_modulate = await import("@gatewai.studio/node-modulate/server");
			if (node_modulate.default) registry.register(node_modulate.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-modulate:", e);
		}

		try {
			const node_noise_generator = await import("@gatewai.studio/node-noise-generator/server");
			if (node_noise_generator.default) registry.register(node_noise_generator.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-noise-generator:", e);
		}

		try {
			const node_note = await import("@gatewai.studio/node-note/server");
			if (node_note.default) registry.register(node_note.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-note:", e);
		}

		try {
			const node_number = await import("@gatewai.studio/node-number/server");
			if (node_number.default) registry.register(node_number.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-number:", e);
		}

		try {
			const node_paint = await import("@gatewai.studio/node-paint/server");
			if (node_paint.default) registry.register(node_paint.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-paint:", e);
		}

		try {
			const node_patch_heal = await import("@gatewai.studio/node-patch-heal/server");
			if (node_patch_heal.default) registry.register(node_patch_heal.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-patch-heal:", e);
		}

		try {
			const node_preview = await import("@gatewai.studio/node-preview/server");
			if (node_preview.default) registry.register(node_preview.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-preview:", e);
		}

		try {
			const node_recorder = await import("@gatewai.studio/recorder/server");
			if (node_recorder.default) registry.register(node_recorder.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/recorder:", e);
		}

		try {
			const node_refine_edge = await import("@gatewai.studio/node-refine-edge/server");
			if (node_refine_edge.default) registry.register(node_refine_edge.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-refine-edge:", e);
		}

		try {
			const node_remove_background = await import("@gatewai.studio/node-remove-background/server");
			if (node_remove_background.default) registry.register(node_remove_background.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-remove-background:", e);
		}

		try {
			const node_resizer_scaler = await import("@gatewai.studio/node-resizer-scaler/server");
			if (node_resizer_scaler.default) registry.register(node_resizer_scaler.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-resizer-scaler:", e);
		}

		try {
			const node_selective_color = await import("@gatewai.studio/node-selective-color/server");
			if (node_selective_color.default) registry.register(node_selective_color.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-selective-color:", e);
		}

		try {
			const node_shadows_highlights = await import("@gatewai.studio/node-shadows-highlights/server");
			if (node_shadows_highlights.default) registry.register(node_shadows_highlights.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-shadows-highlights:", e);
		}

		try {
			const node_shape_generator = await import("@gatewai.studio/node-shape-generator/server");
			if (node_shape_generator.default) registry.register(node_shape_generator.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-shape-generator:", e);
		}

		try {
			const node_signal = await import("@gatewai.studio/node-signal/server");
			if (node_signal.default) registry.register(node_signal.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-signal:", e);
		}

		try {
			const node_smart_cut = await import("@gatewai.studio/node-smart-cut/server");
			if (node_smart_cut.default) registry.register(node_smart_cut.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-smart-cut:", e);
		}

		try {
			const node_stereo_panning = await import("@gatewai.studio/node-stereo-panning/server");
			if (node_stereo_panning.default) registry.register(node_stereo_panning.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-stereo-panning:", e);
		}

		try {
			const node_svg = await import("@gatewai.studio/node-svg/server");
			if (node_svg.default) registry.register(node_svg.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-svg:", e);
		}

		try {
			const node_text = await import("@gatewai.studio/node-text/server");
			if (node_text.default) registry.register(node_text.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-text:", e);
		}

		try {
			const node_text_merger = await import("@gatewai.studio/node-text-merger/server");
			if (node_text_merger.default) registry.register(node_text_merger.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-text-merger:", e);
		}

		try {
			const node_text_to_speech = await import("@gatewai.studio/node-text-to-speech/server");
			if (node_text_to_speech.default) registry.register(node_text_to_speech.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-text-to-speech:", e);
		}

		try {
			const node_tile_offset = await import("@gatewai.studio/node-tile-offset/server");
			if (node_tile_offset.default) registry.register(node_tile_offset.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-tile-offset:", e);
		}

		try {
			const node_unsharp_mask = await import("@gatewai.studio/node-unsharp-mask/server");
			if (node_unsharp_mask.default) registry.register(node_unsharp_mask.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-unsharp-mask:", e);
		}

		try {
			const node_upscaler = await import("@gatewai.studio/node-upscaler/server");
			if (node_upscaler.default) registry.register(node_upscaler.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-upscaler:", e);
		}

		try {
			const node_video_gen = await import("@gatewai.studio/node-video-gen/server");
			if (node_video_gen.default) registry.register(node_video_gen.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-video-gen:", e);
		}

		try {
			const node_video_gen_first_last_frame = await import("@gatewai.studio/node-video-gen-first-last-frame/server");
			if (node_video_gen_first_last_frame.default) registry.register(node_video_gen_first_last_frame.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-video-gen-first-last-frame:", e);
		}

		try {
			const node_video_to_audio = await import("@gatewai.studio/node-video-to-audio/server");
			if (node_video_to_audio.default) registry.register(node_video_to_audio.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-video-to-audio:", e);
		}

		try {
			const node_video_to_music = await import("@gatewai.studio/node-video-to-music/server");
			if (node_video_to_music.default) registry.register(node_video_to_music.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-video-to-music:", e);
		}

		try {
			const node_vignette = await import("@gatewai.studio/node-vignette/server");
			if (node_vignette.default) registry.register(node_vignette.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-vignette:", e);
		}

		try {
			const node_webhook = await import("@gatewai.studio/node-webhook/server");
			if (node_webhook.default) registry.register(node_webhook.default);
		} catch (e) {
			console.warn("Failed to register static node @gatewai.studio/node-webhook:", e);
		}
}

export async function registerStaticRenderers(): Promise<void> {
		try {
			const mod = await import("@gatewai.studio/node-lut/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ApplyLUT", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ApplyLUT", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-lut:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-audio-compressor/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Compressor", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Compressor", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-audio-compressor:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-audio-delay/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Delay", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Delay", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-audio-delay:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-audio-fade/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("AudioFade", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("AudioFade", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-audio-fade:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-audio-noise-gate/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("NoiseGate", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("NoiseGate", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-audio-noise-gate:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-audio-parametric-eq/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ParametricEq", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ParametricEq", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-audio-parametric-eq:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-audio-reverb/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Reverb", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Reverb", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-audio-reverb:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-blur/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Blur", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Blur", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-blur:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-canvas-generator/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("CanvasGenerator", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("CanvasGenerator", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-canvas-generator:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-channel-merger/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ChannelMerger", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ChannelMerger", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-channel-merger:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-channel-splitter/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ChannelSplitter", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ChannelSplitter", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-channel-splitter:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-color-balance/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ColorBalance", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ColorBalance", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-color-balance:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-colorkey/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ColorKey", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ColorKey", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-colorkey:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-compositor/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Compositor", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Compositor", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-compositor:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-corner-pin/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("CornerPin", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("CornerPin", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-corner-pin:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-crop/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Crop", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Crop", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-crop:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-curves/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Curves", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Curves", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-curves:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-displacement-map/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("DisplacementMap", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("DisplacementMap", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-displacement-map:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-extract-frame/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ExtractFrame", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ExtractFrame", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-extract-frame:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-extract-lut/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ExtractLUT", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ExtractLUT", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-extract-lut:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-film-grain/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("FilmGrain", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("FilmGrain", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-film-grain:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-flip/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Flip", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Flip", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-flip:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-gradient-map/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("GradientMap", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("GradientMap", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-gradient-map:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-halftone-screen/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("HalftoneScreen", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("HalftoneScreen", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-halftone-screen:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-high-pass/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("HighPass", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("HighPass", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-high-pass:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-kenburns/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("KenBurns", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("KenBurns", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-kenburns:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-layer-style/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("LayerStyle", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("LayerStyle", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-layer-style:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-levels/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Levels", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Levels", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-levels:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-liquify/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Liquify", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Liquify", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-liquify:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-mask-math/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("MaskMath", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("MaskMath", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-mask-math:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-mesh-warp/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("MeshWarp", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("MeshWarp", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-mesh-warp:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-modulate/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Modulate", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Modulate", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-modulate:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-noise-generator/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("NoiseGenerator", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("NoiseGenerator", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-noise-generator:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-paint/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Paint", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Paint", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-paint:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-patch-heal/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("PatchHeal", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("PatchHeal", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-patch-heal:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-refine-edge/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("RefineEdge", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("RefineEdge", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-refine-edge:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-resizer-scaler/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ResizerScaler", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ResizerScaler", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-resizer-scaler:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-selective-color/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("SelectiveColor", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("SelectiveColor", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-selective-color:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-shadows-highlights/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ShadowsHighlights", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ShadowsHighlights", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-shadows-highlights:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-shape-generator/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("ShapeGenerator", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("ShapeGenerator", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-shape-generator:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-stereo-panning/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("StereoPanning", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("StereoPanning", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-stereo-panning:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-tile-offset/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("TileOffset", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("TileOffset", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-tile-offset:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-unsharp-mask/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("UnsharpMask", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("UnsharpMask", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-unsharp-mask:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-video-to-audio/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("VideoToAudio", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("VideoToAudio", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-video-to-audio:", e);
		}

		try {
			const mod = await import("@gatewai.studio/node-vignette/renderer");
			const def = mod.default as
				| {
						WebGPURenderer?: Parameters<typeof registerWebGPURenderer>[1];
						audioProcessor?: Parameters<typeof audioRegistry.register>[1];
				  }
				| undefined;
			if (def?.WebGPURenderer) {
				registerWebGPURenderer("Vignette", def.WebGPURenderer);
			}
			if (def?.audioProcessor) {
				audioRegistry.register("Vignette", def.audioProcessor);
			}
		} catch (e) {
			console.warn("Failed to register static renderer for @gatewai.studio/node-vignette:", e);
		}
}
