import { defineConfig } from "tsdown";

export default defineConfig({
	entry: ["src/index.ts"],
	format: ["esm"],
	target: "node22",
	platform: "node",
	dts: false,
	clean: true,
	sourcemap: false,
	treeshake: true,
	noExternal: [/^@gatewai\//],
	external: [
		"webgpu",
		"sharp",
		"@napi-rs/canvas",
		"skia-canvas",
		"@resvg/resvg-js",
		"@napi-rs/webcodecs",
		"node-av",
		"@aws-sdk/client-s3",
		"@aws-sdk/s3-request-presigner",
		"@fal-ai/client",
		"@prisma/client",
		"@prisma/adapter-pg",
		"inversify",
		"reflect-metadata",
		"openai",
		"pino",
		"zod",
		"linkedom",
		"nanoid",
		"jiti",
	],
});
